### PR TITLE
Add a few improvements

### PR DESCRIPTION
**Pull request by EDDYMENS**

### CODE REVIEW

**Comment by jcubic** [comment]
Will not merge, you completly rewrite my js code also in php you've changed curly brace in function to be in separated line, I don't like it. Sorry.

**Comment by EDDYMENS** [comment]
Your project your call !

**Comment by EDDYMENS** [comment]
Making the js code independent of jquery will make it highly usable in many projects or so I think

**Comment by jcubic** [comment]
I can make it work with XMLHttpRequest but you did remove automagic creation of  functions based on system.describe by call function with method as string. If you did only replaced $.ajax by XMLHttpRequest I would merge.

**Comment by EDDYMENS** [comment]
Oohk true, I will revert back to your earlier implementation and remove $.ajax . Will send a PR in a couple of hrs

**Pull request closed without merging**
